[package]
name = "admonition"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["crd233"]
license = "MIT"
repository = "https://github.com/crd2333/typst-admonition"
description = "Admonitions for Typst"